version: "3"
services:
  mysql:
    container_name: mysql-server-saa
    image: mysql
    restart: always
    environment:
      - 'MYSQL_DATABASE=authenticate_db'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_PASSWORD=root'
    ports:
      - "3306:3306"
    networks:
      - spring-demo

  rabbitmq:
    container_name: rabbit-server-saa
    image: rabbitmq
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    networks:
      - spring-demo

  spring-app:
    container_name: saa-api
    image: saa/saa:1.0.0
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/authenticate_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge